### ISSUE TITLE
api/me server error

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1010]
```
Processing by Api::V1::UsersController#me as JSON
2015-02-18T19:04:01.289960+00:00 app[web.1]: Completed 500 Internal Server Error in 57.2ms
2015-02-18T19:04:01.309943+00:00 app[web.1]: Processing by Directory::DashboardController#user as HTML
2015-02-18T19:04:01.228468+00:00 app[web.1]: Started GET "/api/users/me" for 67.161.72.143 at 2015-02-18 19:04:01 +0000
2015-02-18T19:04:01.289666+00:00 app[web.1]:   Rendered api/v1/users/me.json.rabl (52.9ms)
2015-02-18T19:04:01.294523+00:00 app[web.1]: 
2015-02-18T19:04:01.294526+00:00 app[web.1]: ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "transcript" does not exist
2015-02-18T19:04:01.294528+00:00 app[web.1]: LINE 1: select * from transcript where id < 0
2015-02-18T19:04:01.294529+00:00 app[web.1]:                       ^
2015-02-18T19:04:01.294531+00:00 app[web.1]: : select * from transcript where id < 0):
2015-02-18T19:04:01.294532+00:00 app[web.1]:     1: object false
2015-02-18T19:04:01.294534+00:00 app[web.1]:     2: 
2015-02-18T19:04:01.294536+00:00 app[web.1]:     3: if current_user
2015-02-18T19:04:01.294537+00:00 app[web.1]:     4:   cur_url = request.protocol + request.host
2015-02-18T19:04:01.294539+00:00 app[web.1]:     5:   if request.port != 80 and request.protocol == 'http://'
2015-02-18T19:04:01.294541+00:00 app[web.1]:   app/models/monthly_usage.rb:30:in `transcripts'
2015-02-18T19:04:01.294542+00:00 app[web.1]:   app/models/concerns/billable.rb:141:in `block in transcript_usage'
2015-02-18T19:04:01.294544+00:00 app[web.1]:   app/models/concerns/billable.rb:139:in `transcript_usage'
2015-02-18T19:04:01.294546+00:00 app[web.1]:   app/views/api/v1/users/me.json.rabl:2:in `_app_views_api_v__users_me_json_rabl__1717777991150897517_70209426385120'
```

**Comment by pkarman** [comment]
should only affect users with zero collections. fixed and deployed.
