### ISSUE TITLE
oembed broken

### ISSUE THREAD

**Issue by pkarman** [popuparchive/pop-up-archive#1091]
https://www.popuparchive.com/oembed?embed=1&format=json&url=https://www.popuparchive.com/tplayer/38020&callback=jQuery191036373954748801074_1430432703168&_=1430432703170

throws missing template exception

```
2015-04-30T22:27:28.496098+00:00 app[web.1]: ActionView::Template::Error (Missing partial embed_player/_tplayer_player_full with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :arb, :rabl]}. Searched in:
2015-04-30T22:27:28.496100+00:00 app[web.1]:   * "/app/app/views"
2015-04-30T22:27:28.496102+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/bundler/gems/activeadmin-28e8a8f36640/app/views"
2015-04-30T22:27:28.496103+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/gems/kaminari-0.16.3/app/views"
2015-04-30T22:27:28.496105+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/gems/doorkeeper-1.4.2/app/views"
2015-04-30T22:27:28.496106+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/gems/switch_user-0.9.5/app/views"
2015-04-30T22:27:28.496108+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/bundler/gems/devise_invitable-3d64d781cd85/app/views"
2015-04-30T22:27:28.496110+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.0.0/gems/devise-3.4.1/app/views"
2015-04-30T22:27:28.496111+00:00 app[web.1]: ):
2015-04-30T22:27:28.496113+00:00 app[web.1]:     1: <div class="pua-tplayer-oembed">
2015-04-30T22:27:28.496115+00:00 app[web.1]:     2: <%= render "embed_player/tplayer_player_full", :formats => [:html], :locals => { :file_id => @file_id } %>
2015-04-30T22:27:28.496116+00:00 app[web.1]:     3: <%= render "embed_player/tplayer_transcript", :formats => [:html], :locals => { :file_id => @file_id } %>
2015-04-30T22:27:28.496118+00:00 app[web.1]:     4: <%= render "layouts/share_modal" %>
2015-04-30T22:27:28.496119+00:00 app[web.1]:     5: <% unless @embed %>
2015-04-30T22:27:28.496120+00:00 app[web.1]:   app/views/oembed/_tplayer.html:2:in `_app_views_oembed__tplayer_html___3526394157603894782_70209434099420'
2015-04-30T22:27:28.496122+00:00 app[web.1]:   app/views/oembed/show.json:12:in `_app_views_oembed_show_json___4176529167388565371_70209437904580'
2015-04-30T22:27:28.496123+00:00 app[web.1]:   app/controllers/oembed_controller.rb:51:in `block (2 levels) in show'
2015-04-30T22:27:28.496125+00:00 app[web.1]:   app/controllers/oembed_controller.rb:46:in `show'
2015-04-30T22:27:28.496126+00:00 app[web.1]: 
```

**Comment by pkarman** [comment]
fixed merge pushed deployed.
