### ISSUE TITLE
[Rake Failure] PUA (RuntimeError) "Public file download failed..."

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1401]
A RuntimeError occurred in background at 2016-03-15 18:20:08 UTC :

  Public file download failed: https://www.popuparchive.com/media/8a1f2a2ef0abff560cec6347127ce5c8/0/public/audio_file/57072/FR-ON-SF-03-I%C3%A7i-%C3%A0-Dons-Butcher-Shop.mp3.
  /app/lib/utils.rb:277:in `download_public_file'

  -------------------------------
Backtrace:
-------------------------------

  /app/lib/utils.rb:277:in `download_public_file'
  /app/lib/utils.rb:153:in `download_file'
  /app/app/models/tasks/voicebase_transcribe_task.rb:475:in `download_audio_file'
  /app/app/models/tasks/voicebase_transcribe_task.rb:31:in `process'
  /app/app/workers/process_task_worker.rb:12:in `block in perform'
  /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
  /app/app/workers/process_task_worker.rb:9:in `perform'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
  /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/lock/while_executing.rb:20:in `synchronize'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-unique-jobs-4.0.7/lib/sidekiq_unique_jobs/server/middleware.rb:18:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:86:in `do_defer'
  /app/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:37:in `process'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
  /app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {:message=>
    {"retry"=>25,
     "queue"=>"default",
     "unique"=>"until_and_while_executing",
     "class"=>"ProcessTaskWorker",
     "args"=>[483144],
     "jid"=>"01374e191336bbbce5327e42",
     "enqueued_at"=>1456297031.1357336,
     "unique_prefix"=>"uniquejobs",
     "unique_args"=>[483144],
     "unique_digest"=>"uniquejobs:f0eddf6f2de53b8efb7da04c221896d2",
     "error_message"=>
      "Public file download failed: https://www.popuparchive.com/media/8a1f2a2ef0abff560cec6347127ce5c8/0/public/audio_file/57072/FR-ON-SF-03-I%C3%A7i-%C3%A0-Dons-Butcher-Shop.mp3.",
     "error_class"=>"RuntimeError",
     "failed_at"=>1456297042.0447063,
     "retry_count"=>25,
     "retried_at"=>1458066008.2755497}}

**Comment by AndersEverett** [comment]
Caps ia?
