### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1406]
An OpenSSL::SSL::SSLError occurred in background at 2016-03-21 01:23:40 UTC :

  SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `connect'

  -------------------------------
Backtrace:
-------------------------------

  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `connect'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:918:in `connect'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:851:in `start'
  /home/puauser/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/net/http.rb:1367:in `request'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/httparty-0.13.5/lib/httparty.rb:506:in `head'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/httparty-0.13.5/lib/httparty.rb:588:in `head'
  /home/puauser/audiosear.ch/app/workers/file_cleanup_worker.rb:9:in `perform'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:86:in `do_defer'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:37:in `process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {:message=>
    {"retry"=>10,
     "queue"=>"default",
     "class"=>"FileCleanupWorker",
     "args"=>[1714],
     "jid"=>"6ce37a6d415fd7a92308c168",
     "enqueued_at"=>1458482736.9948106,
     "error_message"=>
      "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed",
     "error_class"=>"OpenSSL::SSL::SSLError",
     "failed_at"=>1458483393.7768323,
     "retry_count"=>3,
     "retried_at"=>1458523419.5963576}}

**Comment by annewootton** [comment]
Fixed cert, error went away.
