### ISSUE TITLE
Why did nudger choke on Transcribe finish_task? Error from AWS 

### ISSUE THREAD

**Issue by AndersEverett** [popuparchive/pop-up-archive#1409]
rake aborted!
Excon::Errors::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => ""
  :headers       => {
    "Content-Type"      => "application/xml"
    "Date"              => "Wed, 23 Mar 2016 01:03:19 GMT"
    "Server"            => "AmazonS3"
    "Transfer-Encoding" => "chunked"
    "x-amz-id-2"        => "9mePN0S+Dsxd89/vOgGfX+3tpxuXXIlcccQGzA5CjmVGt0O7ymoZl0Znc1V3ytgSl3EYdYChwbI="
    "x-amz-request-id"  => "09216351C6173391"
  }
  :local_address => "172.31.33.65"
  :local_port    => 53705
  :reason_phrase => "Forbidden"
  :remote_ip     => "54.231.82.52"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:6:in `response_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:236:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/idempotent.rb:26:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/middlewares/base.rb:10:in `error_call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:256:in `rescue in request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/excon-0.45.3/lib/excon/connection.rb:204:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-core-1.30.0/lib/fog/core/connection.rb:81:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-aws-0.4.1/lib/fog/aws/storage.rb:596:in `_request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-aws-0.4.1/lib/fog/aws/storage.rb:591:in `request'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-aws-0.4.1/lib/fog/aws/requests/storage/head_object.rb:41:in `head_object'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/fog-aws-0.4.1/lib/fog/aws/models/storage/files.rb:101:in `head'
/home/pua/pop-up-archive/lib/utils.rb:134:in `private_file_exists?'
/home/pua/pop-up-archive/lib/utils.rb:104:in `get_private_file'
/home/pua/pop-up-archive/app/models/task.rb:188:in `get_file'
/home/pua/pop-up-archive/app/models/tasks/transcribe_task.rb:21:in `finish_task'
/home/pua/pop-up-archive/app/models/task.rb:61:in `block (2 levels) in <class:Task>'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/eval_helpers.rb:79:in `call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/eval_helpers.rb:79:in `evaluate_method'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/callback.rb:191:in `block in run_methods'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `each'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/callback.rb:190:in `run_methods'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/callback.rb:159:in `call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block (2 levels) in after'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `each'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:450:in `block in after'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `catch'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:448:in `after'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:251:in `run_callbacks'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:127:in `run_callbacks'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:212:in `run_callbacks'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:186:in `within_transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block in around_save'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:530:in `block in transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:529:in `transaction'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:501:in `around_save'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:483:in `save'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:154:in `block (2 levels) in run_actions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:154:in `each'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:154:in `block in run_actions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:170:in `catch_exceptions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:148:in `run_actions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:60:in `perform'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/transition.rb:219:in `perform'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/event.rb:172:in `fire'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/event.rb:247:in `block in add_actions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/event.rb:252:in `block in add_actions'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
/home/pua/pop-up-archive/app/models/tasks/transcribe_task.rb:73:in `recover!'
/home/pua/pop-up-archive/lib/tasks/fixer.rake:66:in `block (4 levels) in <top (required)>'
/home/pua/pop-up-archive/lib/tasks/fixer.rake:54:in `each'
/home/pua/pop-up-archive/lib/tasks/fixer.rake:54:in `block (3 levels) in <top (required)>'
/home/pua/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-4.2.3/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/pua/pop-up-archive/lib/tasks/fixer.rake:53:in `block (2 levels) in <top (required)>'
/home/pua/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/home/pua/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => fixer:nudge
(See full trace by running task with --trace)
  Rendered /home/pua/.rvm/gems/ruby-2.0.0-p598/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.3ms)
  Rendered /home/pua/.rvm/gems/ruby-2.0.0-p598/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.4ms)
  Rendered /home/pua/.rvm/gems/ruby-2.0.0-p598/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_data.text.erb (0.5ms)
  Rendered /home/pua/.rvm/gems/ruby-2.0.0-p598/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /home/pua/.rvm/gems/ruby-2.0.0-p598/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/background_exception_notification.text.erb (13.7ms)

**Comment by AndersEverett** [comment]
Error from S3:
[fog][WARNING] fog: the specified s3 bucket name(neal-adams-comic-book-artist.P5aRq7.popuparchive.org) is not a valid dns name, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
[fog][WARNING] fog: followed redirect to ia801509.s3dns.us.archive.org, connecting to the matching region will be more performant
[fog][WARNING] fog: the specified s3 bucket name(neal-adams-comic-book-artist.P5aRq7.popuparchive.org) is not a valid dns name, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by AndersEverett** [comment]
See collection 431. This could be because this is an internet archive storage account.

**Comment by AndersEverett** [comment]
See the tasks on this : https://www.popuparchive.com/collections/431/items/53605

**Comment by AndersEverett** [comment]
This issue is a bit of a puzzle. I ran finish_task on the Transcribe Task that was previously breaking the nudger, and the task finished immediately with a complete transcript. Without the opportunity to recreate the error, I'm not sure there's an immediate solution here. I was also able to download the file from aws, re-upload it, and create a new item with it, which completed all tasks without issue. Lastly, I tried creating an "internet archive" collection, with storage configuration set as such. When uploaded to this, the file completed all tasks (including a manually created google transcribe task) without errors. I vote to close this and monitor for reoccurrence.

**Comment by annewootton** [comment]
Word. Might be something we've fixed in the interim.

**Comment by baileyspace** [comment]
Reviving this. I just manually failed task 520410 because it was hanging up the nudger. Same error as previous failure.
