### ISSUE TITLE
(NameError) undefined local variable or method `copy_to_item_storage

### ISSUE THREAD

**Issue by annewootton** [popuparchive/pop-up-archive#1412]
Possibly related to #1400, #1401:

A NameError occurred in background at 2016-03-27 19:15:32 UTC :

  undefined local variable or method `copy_to_item_storage' for #<AudioFile:0x0000000ceafc48>
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activemodel/lib/active_model/attribute_methods.rb:433:in `method_missing'

  -------------------------------
Backtrace:
-------------------------------

  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activemodel/lib/active_model/attribute_methods.rb:433:in `method_missing'
  /home/puauser/audiosear.ch/app/models/audio_file.rb:206:in `process_update_file'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:253:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:253:in `block in conditional'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:506:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:506:in `block in call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:506:in `each'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:506:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activesupport/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/transactions.rb:314:in `committed!'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/transactions.rb:220:in `transaction'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/bundler/gems/rails-23d555930c4f/activerecord/lib/active_record/transactions.rb:291:in `save!'
  /home/puauser/audiosear.ch/app/workers/file_cleanup_worker.rb:16:in `perform'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/logging.rb:22:in `with_context'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `call'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:108:in `stats'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:47:in `block in process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:86:in `do_defer'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/sidekiq-2.17.7/lib/sidekiq/processor.rb:37:in `process'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
  /home/puauser/.rvm/gems/ruby-2.0.0-p576/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {:message=>
    {"retry"=>10,
     "queue"=>"default",
     "class"=>"FileCleanupWorker",
     "args"=>[32179],
     "jid"=>"6ba0f5cafd050b58528e92d6",
     "enqueued_at"=>1459092742.8423426,
     "error_message"=>
      "undefined local variable or method `copy_to_item_storage' for #<AudioFile:0x0000000ceafc48>",
     "error_class"=>"NameError",
     "failed_at"=>1459106132.015575,
     "retry_count"=>0}}

**Comment by annewootton** [comment]
Scratch that, this is an Audiosear.ch error, not PUA.
